-- r55 canonical fields schema. 過去のSpread/DB列互換は考慮しません。
DROP TABLE IF EXISTS business_cards;
CREATE TABLE business_cards (
  record_id TEXT PRIMARY KEY,
  record_status TEXT NOT NULL DEFAULT 'ACTIVE',
  revision INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  updated_by TEXT NOT NULL DEFAULT '',
  deleted_at TEXT NOT NULL DEFAULT '',
  deleted_by TEXT NOT NULL DEFAULT '',
  company_name TEXT NOT NULL DEFAULT '',
  company_name_kana TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  first_name TEXT NOT NULL DEFAULT '',
  last_name_kana TEXT NOT NULL DEFAULT '',
  first_name_kana TEXT NOT NULL DEFAULT '',
  department_name TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  phone_number TEXT NOT NULL DEFAULT '',
  mobile_number TEXT NOT NULL DEFAULT '',
  fax_number TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  postal_code TEXT NOT NULL DEFAULT '',
  address_text TEXT NOT NULL DEFAULT '',
  website_url TEXT NOT NULL DEFAULT '',
  exchanged_by_last_name TEXT NOT NULL DEFAULT '',
  exchanged_by_first_name TEXT NOT NULL DEFAULT '',
  exchange_date TEXT NOT NULL DEFAULT '',
  exchange_place TEXT NOT NULL DEFAULT '',
  group_name TEXT NOT NULL DEFAULT '',
  tags TEXT NOT NULL DEFAULT '',
  memo TEXT NOT NULL DEFAULT '',
  image_storage_provider TEXT NOT NULL DEFAULT '',
  image_drive_file_id TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  original_image_drive_file_id TEXT NOT NULL DEFAULT '',
  original_image_url TEXT NOT NULL DEFAULT '',
  cropped_image_drive_file_id TEXT NOT NULL DEFAULT '',
  cropped_image_url TEXT NOT NULL DEFAULT '',
  image_file_name TEXT NOT NULL DEFAULT '',
  image_mime_type TEXT NOT NULL DEFAULT '',
  image_size_bytes TEXT NOT NULL DEFAULT '',
  image_width TEXT NOT NULL DEFAULT '',
  image_height TEXT NOT NULL DEFAULT '',
  image_folder_id TEXT NOT NULL DEFAULT '',
  image_quality_score TEXT NOT NULL DEFAULT '',
  brightness_status TEXT NOT NULL DEFAULT '',
  blur_status TEXT NOT NULL DEFAULT '',
  frame_status TEXT NOT NULL DEFAULT '',
  skew_status TEXT NOT NULL DEFAULT '',
  contour_status TEXT NOT NULL DEFAULT '',
  retake_required TEXT NOT NULL DEFAULT '',
  retake_reason TEXT NOT NULL DEFAULT '',
  quality_warnings TEXT NOT NULL DEFAULT '',
  crop_box TEXT NOT NULL DEFAULT '',
  ocr_text TEXT NOT NULL DEFAULT '',
  ocr_status TEXT NOT NULL DEFAULT '',
  ocr_language TEXT NOT NULL DEFAULT '',
  ocr_processed_at TEXT NOT NULL DEFAULT '',
  ocr_engine TEXT NOT NULL DEFAULT '',
  ocr_error_message TEXT NOT NULL DEFAULT '',
  ocr_source_image_type TEXT NOT NULL DEFAULT '',
  search_key TEXT NOT NULL DEFAULT '',
  search_text TEXT NOT NULL DEFAULT '',
  name_sort_key TEXT NOT NULL DEFAULT '',
  company_sort_key TEXT NOT NULL DEFAULT '',
  email_lower TEXT NOT NULL DEFAULT '',
  phone_digits TEXT NOT NULL DEFAULT '',
  data_json TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_business_cards_status_updated ON business_cards(record_status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_business_cards_search_key ON business_cards(search_key);
CREATE INDEX IF NOT EXISTS idx_business_cards_search_text ON business_cards(search_text);
CREATE INDEX IF NOT EXISTS idx_business_cards_email_lower ON business_cards(email_lower);
CREATE INDEX IF NOT EXISTS idx_business_cards_phone_digits ON business_cards(phone_digits);
